#!/bin/bash

# This script will install League if it is not already installed.
# If League is installed then the Client will be started

if [ -f "/root/.LoL64/drive_c/Riot Games/League of Legends/LeagueClient.exe" ];then
    echo "League is already installed. Starting"
    WINEPREFIX=~/.LoL64 wine "/root/.LoL64/drive_c/Riot Games/League of Legends/LeagueClient.exe"
else
    echo "League doesn't appear to be installed. Starting installer"
    WINEPREFIX=~/.LoL64 wine /root/lol.exe
fi

while(true)
do

    echo "League is running in a container :)"
    sleep 60

done
